export * from './src/app/core/models/reserva/reserva.model';
export * from './src/app/core/models/reserva/criar-reserva-online-request.model';
export * from './src/app/core/models/reserva/criar-reserva-presencial-request.model';
export * from './src/app/core/models/reserva/associar-placa-request.model';
export * from './src/app/core/models/reserva/checkout-request.model';
export * from './src/app/core/models/reserva/cupom-entrada.model';
export * from './src/app/core/models/reserva/cupom-saida.model';
export * from './src/app/core/models/reserva/whats-app-response.model';
export * from './src/app/core/models/reserva/reserva-filtros.model';
